Add VS2022 solution
1dot13/source pull request #140
Opened 2023-05-06 19:03 UTC by NorthFury

I removed the already committed user local project settings before adding adding a rule for them to gitignore.
The `ext\VFS\build\` path was ignored and shouldn't be. I updated the gitignore file to be more specific in regards to the build directories.
I added a VS2022 solution that builds to VS2022 instead of VS2013.

2023-05-07 09:54 UTC, Asdow commented
We've switched over to cmake, so the solution files are no longer necessary IIRC.
@majcosta was this correct?

2023-05-07 10:21 UTC, majcosta commented
> We've switched over to cmake, so the solution files are no longer necessary IIRC. @majcosta was this correct?

Yes. I am very overdue with the PR to clean them up, sorry.

2023-05-07 12:44 UTC, majcosta requested changes
first two commits are great, thank you! last one can be dropped, sorry for your trouble

2023-05-07 12:44 UTC, majcosta commented on .gitignore
> +/lib/
these two aren't needed anymore, if you want to remove them while you're at it I'd be grateful

2023-05-07 12:44 UTC, majcosta commented on .gitignore
> +*.vcxproj.user
same as above

2023-05-08 08:39 UTC, NorthFury commented
I'm closing this PR since we're removing all visual studio solution and project files. I can open up a new one if there will be any changes still needed.

2023-05-08 08:39 UTC, closed without merging

2023-05-08 08:56 UTC, majcosta commented
Like I said, the first two commits are a good change. There's no need for a new PR, you can just drop the `add vs2022 solution` and update this one.

If you're unsure how to do it, this is a good StackOverflow answer: https://stackoverflow.com/a/51400593

2023-05-08 09:09 UTC, NorthFury commented
I know how to use git. The main purpose of this PR was to add a VS22 solution. Every other change was supporting that purpose and ensuring there is a good dev experience with it.

For the changes you mentioned to keep:
* you are already deleting the user project files in your PR.
* most of my changes for the gitignore file are obsolete already

I'll look over how the new dev experience is and update the gitignore file afterwards to something that fits the needs.