make gitignore Visual Studio definitions more specific
1dot13/source pull request #144
Opened 2023-05-15 21:09 UTC by NorthFury

This change has gitignore only ignore files from the repo root directory.

2023-05-18 19:17 UTC, majcosta requested changes

2023-05-18 19:17 UTC, majcosta commented on .gitignore
> +/out/
after #141 these two aren't necessary anymore, you can remove

2023-05-18 19:17 UTC, majcosta commented on .gitignore
>  cmake-build-*/
you can prepend a `/` to these too

2023-05-18 19:18 UTC, majcosta commented on .gitignore
>  cmake-build-*/
GitHub isn't being helpful, but I meant to include the `.idea` line in that as well

2023-05-20 22:49 UTC, NorthFury commented on .gitignore
> +/out/
With the import procedure for Visual Studio 2022, the `CMakeSettings.json` file is generated, together with a `/out/` directory. I think we should keep the /out/ line for now.

2023-05-20 22:55 UTC, majcosta commented on .gitignore
> +/out/
sure

2023-05-20 22:55 UTC, majcosta approved these changes

2023-05-20 22:56 UTC, merged